# Generated by Django 2.2.6 on 2019-10-19 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseBrickDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(blank=True, max_length=19, verbose_name='Key')),
                ('computer_name', models.CharField(blank=True, max_length=250, verbose_name='Computer name')),
                ('id_program', models.CharField(blank=True, max_length=8, verbose_name='ID program')),
                ('email', models.EmailField(blank=True, default='xxx@xxx.xx', max_length=254, verbose_name='E-mail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Licenses BrickDesigner_BD001',
                'verbose_name_plural': 'Licenses BrickDesigner_BD001',
            },
        ),
    ]
